spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    key: ${JWT_KEY}
    live:
      accessToken: ${ACCESS_TOKEN_TIME}

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${BUCKET}
      region:
        static: ${STATIC}
      stack:
        auto: false

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB