spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
    properties:
      show_sql: true
=======
      ddl-auto: create
    show-sql: true
>>>>>>> 3511d025b32161eaa428ef92901e43ece7a6ebd2

  jackson:
    property-naming-strategy: SNAKE_CASE

<<<<<<< HEAD
  jwt:
    key: ${JWT_KEY}
    live:
      accessToken: ${ACCESS_TOKEN_TIME}

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${BUCKET}
      region:
        static: ${STATIC}
      stack:
        auto: false

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
=======
  jwt :
    secretKey : ${JWT_KEY}
    accessExp : ${ACCESS_TOKEN_TIME}
>>>>>>> 3511d025b32161eaa428ef92901e43ece7a6ebd2
